
 
 export const UPDATE_CURRENT_PAGE = "UPDATE_CURRENT_PAGE";
 export const UPDATE_TOTOAL_PAGE = "UPDATE_TOTOAL_PAGE";

 export const UPDATE_CHARACTER_NAME = "UPDATE_CHARACTER_NAME";
 export const UPDATE_CHARACTER_GENDER = "UPDATE_CHARACTER_GENDER";
 export const UPDATE_CHARACTER_SPECIES = "UPDATE_CHARACTER_SPECIES";
 export const UPDATE_CHARACTER_STATUS = "UPDATE_CHARACTER_STATUS";

 export const UPDATE_LOCATION_NAME = "UPDATE_LOCATION_NAME";
 export const UPDATE_LOCATION_DIMENSION = "UPDATE_LOCATION_DIMENSION";
 export const UPDATE_LOCATION_TYPE = "UPDATE_LOCATION_TYPE";

 export const UPDATE_EPISODE_NAME = "UPDATE_EPISODE_NAME";
 export const UPDATE_EPISODE_CODE = "UPDATE_EPISODE_CODE";

 export const UPDATE_CHARACTER_DATA="UPDATE_CHARACTER_DATA";
 export const UPDATE_LOCATION_DATA="UPDATE_LOCATION_DATA";
 export const UPDATE_EPISODE_DATA="UPDATE_EPISODE_DATA";
 export const UPDATE_PROFILE_DATA="UPDATE_PROFILE_DATA";

export const UPDATE_SHOW_LOCATION_CARD = "UPDATE_SHOW_LOCATION_CARD";
export const UPDATE_SHOW_EPISODE_CARD = "UPDATE_SHOW_EPISODE_CARD";